# Site settings
title: Glouglou
email: contact@baud-jules.me
description: > # this means to ignore newlines until "baseurl:"
  Article proposés par Jules Baud sur la programmation , C et C++, Java , Python
  Ruby et autres langages de programmation. Le système GNU/Linux sera aussi traité
  des artices pour configurer Github et git en particulier seront bientôt ajoutés.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jules-baud.me" # the base hostname & protocol for your site
twitter_username: baudjules
github_username:  Jbaud

# Build settings
markdown: kramdown
